### PR TITLE
update

### PR DESCRIPTION
**Pull request by Anniedevkiller**
I want to make a pull request

### CODE REVIEW

**Comment by MartyOfMCA** [comment]
Hi there, kindly make sure your directory name is only lowercase. And do well to add your `README.md` file

**Comment by Anniedevkiller** [comment]
Hello there,
I have added my readme file when pushing.

**Review by MartyOfMCA — CHANGES_REQUESTED** [review]
I still can't find your `README.md` file. Also, check the indentation and spacing of your `calc.c` source code file

**Comment by Anniedevkiller** [comment]
Hello Marty
I have made a pull request and also i have put my readme, did my directory in lowercase
Good day.

**Comment by MartyOfMCA** [comment]
I can still see your directory name with uppercase letters, please. Kindly rectify that. And there seems to be a problem with your code's indentation. Could you kindly fix that as well to make it easier to read?

**Comment by Anniedevkiller** [comment]
Hello Martin,
I have corrected the mistake
Thank you.

**Comment by MartyOfMCA** [comment]
Kindly make sure you only have the `anniedevkiller` directory with your `README.md` file along with your code files. Kindly delete the `C` directory

**Review by MartyOfMCA — APPROVED** [review]

**Pull request merged**
