### PR TITLE
This calculator is for demo project

### PR DESCRIPTION
**Pull request by Namujibril**

### CODE REVIEW

**Comment by MartyOfMCA** [comment]
Hi there, kindly make sure you remove all needed files (binary, executables like the `.CAL-README.md.swp` in your directory). Also ensure your directory is names in lowercases @Namujibril

**Comment by Namujibril** [comment]
I have changed as was directed, now how can I go with it again?

**Comment by MartyOfMCA** [comment]
Noticed your changes. I would like for you to do the following:

1. Remove the entire directory Namujibril from this pull request. The directory starting with an uppercase
2. Remove the .swp file and any other file which is not a source code file
3. Rename your readme file from CAL-README.md to README.md.

You should eventually have one directory called namujibril with your README.md and your source code files

**Comment by MartyOfMCA** [comment]
You're almost there. Rename your readme file to README.md. Here's some code to help you out

In your directory namujibril, use the command `mv Cal-README.md README.md` to rename the README file

**Comment by Namujibril** [comment]
Yes, I'm done with renaming.
I hope now I'm in?

**Comment by MartyOfMCA** [comment]
Great work @Namujibril

**Pull request merged**
