### PR TITLE
rename bettCollins directory

### PR DESCRIPTION
**Pull request by reecevinto**

### CODE REVIEW

**Comment by MartyOfMCA** [comment]
Hi @reecevinto, I've seen your changes, and here's what you need to do:

1. Remove the executable file
2. Change the name of your markdown file to `README.md` instead of `collins.md`
3. Make sure your directory name is made of lowercase only

**Comment by reecevinto** [comment]
thank you for the review marty working on it

**Comment by DestinedCodes** [comment]
@MartyOfMCA I'm closing this PR as a duplicate cos @reecevinto already opened a new one which was from his special branch rather than main. He still have same errors you mentioned I I think you can assist @Certifieddonnie with the review

**Comment by reecevinto** [comment]
Hello am having problems removing the executable file . How do i go about it?

**Pull request closed without merging**
