### PR TITLE
Ukasquared

### PR DESCRIPTION
**Pull request by Ukasquared**
code modified and readme file added

### CODE REVIEW

**Comment by MartyOfMCA** [comment]
Hi, you still have PR https://github.com/ALX-SE-Algorithmia/Demo-Project/pull/44 open with some requests I added. Could you close one of them so we can review the other?

https://github.com/ALX-SE-Algorithmia/Demo-Project/pull/44 has no `README/md` file whereas this PR has the executable file, `a.out`, added.

Should you choose to close https://github.com/ALX-SE-Algorithmia/Demo-Project/pull/44, then make sure you remove `a.out` from this PR. But should you decide to close this PR then I'll suggest you add the `README.md` to https://github.com/ALX-SE-Algorithmia/Demo-Project/pull/44

**Comment by Ukasquared** [comment]
Thank you, I was thinking the user can easily run the executable file

**Comment by MartyOfMCA** [comment]
I understand that perfectly. But with the necessary instructions on compiling and running your program in your `README.md`, anyone can quickly run your source code to generate the executable on their system. It's pretty scary to download an executable from the internet without knowing what it entails.

**Comment by Ukasquared** [comment]
Ok, thanks for the clarification.

**Comment by Ukasquared** [comment]
closed to request a new merge

**Pull request closed without merging**
