### PR TITLE
collins

### PR DESCRIPTION
**Pull request by reecevinto**

### CODE REVIEW

**Comment by MartyOfMCA** [comment]
Hi @reecevinto, kindly change your directory name to lowercase. I also noticed you have an open PR https://github.com/ALX-SE-Algorithmia/Demo-Project/pull/37. Kindly close https://github.com/ALX-SE-Algorithmia/Demo-Project/pull/37 if you don't need it to be reviewed

**Comment by Certifieddonnie** [comment]
> Hi @reecevinto, kindly change your directory name to lowercase. I also noticed you have an open PR #37. Kindly close #37 if you don't need it to be reviewed

Hello @reecevinto kindly change your directory name to your username in lowercase.

**Review by Certifieddonnie — CHANGES_REQUESTED** [review]
Change your directory name to your username in lowercase

**Comment by dohoudaniel** [comment]
Hi @reecevinto.
I shall close this PR, and open another one.

**Pull request closed without merging**
